# Permalinks
permalink:           pretty

# Setup
title:               Daehwan's blog
# tagline:             The Jekyll Butler
url:                 http://daehwann.github.io
paginate:            1
baseurl:             "/blog"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Daehwan Cho
  # url:               https://twitter.com/mdo
  email:             daehwann@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/daehwann/blog
disqus:              daehwan-blog
google_analytics:    UA-83903045-5

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
